### ISSUE TITLE
Proving and Verification trait methods can take a reference to ACIR

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#101]
# Problem

Currently in our prove/verify methods, we take ownership of a `Circuit`. Given that these methods will not apply optimisations, we should not need to take ownership as we are not planning to modify the struct in that method. Upstream callers of this method may need to unecessarily clone the whole circuit.

# Solution

Change those methods to take `&Circuit`
# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

**Comment by TomAFrench** [comment]
Ah, this would be very helpful for the build-artifact work I'm doing. Made a PR for this.
