### ISSUE TITLE
Consider removing `Linear` struct

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm#130]
# Problem

The `Linear` struct is dead code as we always use the more general `Expression`.

# Solution

We should decide whether this is wanted in future and potentially remove it.

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

`Linear` is in the public interface of `acir` so this would be a breaking change.

**Comment by TomAFrench** [comment]
@kevaundray We don't seem to use this ever and just use `Expression`. Do you see any reason to not trim this code?

**Comment by kevaundray** [comment]
Yeah this is no longer being used and can be removed -- It's usefulness was because when we have an Expression of the form `mx+c` we could apply certain optimizations -- now we are simply just checking for `Linear` property on an Expression instead of encoding it in a struct.
