### ISSUE TITLE
Remove `prove_with_meta` and `verify_from_cs`

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm#139]
### Problem

@vezenovm said we don't use `prove_with_meta` and `verify_from_cs` anymore. We should remove them from the `ProofSystemCompiler` trait so we don't need to implement them in backends.

### Proposed solution

Remove them, as they are already marked as deprecated. 

### Additional context

Ref https://github.com/noir-lang/aztec_backend/pull/82

**Comment by TomAFrench** [comment]
Yep, these were deprecated in 0.5.0 so removal in 0.7.0 fits Kev's "deprecation -> removal" schedule.

The only other currently developed backend that I know of (gnark) supports the pk/vk methods so no reason to keep this around.
