### ISSUE TITLE
Remove all deprecated methods

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#147]
### Problem

Its been more than two releases since all methods have been marked as deprecated, so we can successfully remove them.

### Proposed solution

Remove deprecated methods and make corresponding updates in our main consumer; Noir.

To make the change less disruptive, we could remove usage of them in Noir first. The usage of  `is_opcode_supported` seems to be the most non-trivial change

**Comment by joss-aztec** [comment]
Preexisting work to remove `default_is_opcode_supported` usage: https://github.com/noir-lang/noir/pull/1339/commits/8ca4ec6205a529c4c46f36e3d6bad6af1e41ae2a

**Comment by joss-aztec** [comment]
Linking PR: https://github.com/noir-lang/noir/pull/1339
