### ISSUE TITLE
Should we deprecate Expression for Mul/Add operations?

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#18]
The main disadvantage is that there will need to be another pass that optimises many mul and adds into an expression that is suited for the particular proving system.

Another idea is to introduce MulN and AddN which allows for N inputs, then we have a pass which combines this into the relevant expression.

The advantage is that we then support more than a degree polynomial.

The pass would take the degree and the fan-in as an input, degree would let us know how many terms we can keep in the Mul Opcode, the fan-in variable will let us know how many inputs we can keep in the AddN opcode.  We would also need another variable to describe how to Mul and Add opcodes into Expressions.

**Comment by kevaundray** [comment]
MulN opcode would take one coefficient and N variables.
AddN would take N tuples of one coefficient and one variable

**Comment by guipublic** [comment]
Could you clarify your proposal?
