### ISSUE TITLE
`Backend::black_box_function_supported` does not satisfy type `IsOpcodeSupported`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm#183]
### Aim

The method `black_box_function_supported` was added to the backends so that ACVM can query which opcodes it supports and fallback as necessary. 

I'm wanting to pass the method `black_box_function_supported` which is defined on my backend into `acvm::compiler::compile` so that I can use the most accurate spec of what my backend supports.

### Expected behavior

I should be able to pass in the method on the backend so that the ACVM uses the set of black box functions which I have marked as available (as opposed to using the function `acvm::default_is_opcode_supported`).

### Bug

If I were to try to pass in `Backend::black_box_function_supported` however I run into two issues
1. `IsOpcodeSupported` accepts an `Opcode` as an argument but `black_box_function_supported` expects a `BlackBoxFunc`.
2. `IsOpcodeSupported` specifies a function pointer however this prevents us from passing a closure.

Due to 2., trying to use `Backend::black_box_function_supported` anyway results in the error below

```
error[E0308]: mismatched types
   --> crates/nargo_cli/src/cli/compile_cmd.rs:143:65
    |
143 |         acvm::compiler::compile(circuit, backend.np_language(), |opcode |{backend.black_box_function_supported(opcode)}).unwrap();
    |         -----------------------                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected fn pointer, found closure
    |         |
    |         arguments to this function are incorrect
    |
    = note: expected fn pointer `for<'a> fn(&'a acvm::acir::circuit::Opcode) -> bool`
                  found closure `[closure@crates/nargo_cli/src/cli/compile_cmd.rs:143:65: 143:74]`

```

This then means that we have to define a function near where we're calling `acvm::compiler::compile` similar to

```rust
fn is_opcode_supported(opcode: &Opcode) -> bool {
    let backend = crate::backends::ConcreteBackend;
    match opcode {
       Opcode::Arithmetic(_)
            | Opcode::Directive(_)
            | Opcode::Block(_)
            | Opcode::ROM(_)
            | Opcode::RAM(_)
            | Opcode::Oracle(_) => true,
        Opcode::BlackBoxFuncCall(black_box_func) => {
            backend.black_box_function_supported(&black_box_func.name)
        }
    }
}
```

This in turn means that we need to hardcode the backend which we are using to call this function which isn't workable.

### To reproduce

1.
2.
3.
4.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
> @guipublic and I spoke about this yesterday and agreed that it would be cleaner to pass in a `&impl Backend` to `acvm::compile` instead.

Its cleaner, but its not clearer since you don't need the proof and verification
