### ISSUE TITLE
[Bug/Security] Out-of-memory (OOM) panic while reading a circuit

### ISSUE THREAD

**Issue by pventuzelo** [noir-lang/acvm#187]
### Aim

We (@fuzzinglabs & @lambdaclass) found an out-of-memory issue in acvm 0.8.1 while reading a circuit.

### Expected behavior

It should not crash.

## Root cause

```
memory allocation of 725253292032 bytes failed
[1]    1194841 abort (core dumped)
```

Before calling `Vec::with_capacity`, the `num_opcodes` value should be checked and sanitized.

Related code: https://github.com/noir-lang/acvm/blob/ee59c9efe9a54ff6b97e4daaebf64f3e327e97d9/acir/src/circuit/mod.rs#L118

## Detailed behavior
``` sh
GDB backtrace:
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
memory allocation of 725253292032 bytes failed

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50 ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c4c859 in __GI_abort () at abort.c:79
#2  0x00005555555ab2b7 in std::sys::unix::abort_internal () at library/std/src/sys/unix/mod.rs:350
#3  0x000055555555ddd7 in std::process::abort () at library/std/src/process.rs:2138
#4  0x00005555555ab72e in std::alloc::rust_oom () at library/std/src/alloc.rs:356
#5  0x00005555555ab737 in std::alloc::_::__rg_oom () at library/std/src/alloc.rs:351
#6  0x00005555555bfd27 in alloc::alloc::handle_alloc_error::rt_error () at library/alloc/src/alloc.rs:385
#7  0x000055555555eec7 in alloc::alloc::handle_alloc_error () at library/alloc/src/alloc.rs:389
#8  0x000055555556afbd in alloc::raw_vec::RawVec<T,A>::allocate_in (capacity=2833020672, init=alloc::raw_vec::AllocInit::Uninitialized, alloc=...) at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/alloc/src/raw_vec.rs:190
#9  0x0000555555586c28 in alloc::raw_vec::RawVec<T,A>::with_capacity_in () at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/alloc/src/raw_vec.rs:131
#10 alloc::vec::Vec<T,A>::with_capacity_in () at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/alloc/src/vec/mod.rs:675
#11 alloc::vec::Vec<T>::with_capacity (capacity=2833020672) at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/alloc/src/vec/mod.rs:482
#12 0x0000555555568371 in acir::circuit::Circuit::read (reader=...) at /home/scop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/acir-0.8.1/src/circuit/mod.rs:118
#13 0x000055555555fe2e in noir_fuzzing::oom_circuit_read () at src/main.rs:30
#14 0x000055555555fdf6 in noir_fuzzing::main () at src/main.rs:8
```

### To reproduce

Testing program:
``` rust
use acvm::acir::circuit::Circuit;

fn main() {
    let data = b"\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x77\xdc\xa8\x37\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0\x80\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x04";
    let circuit = Circuit::read(&data[..]);
}

```

### Versions

-  acvm = "0.8.1"
-  cargo 1.70.0-nightly (15d090969 2023-03-21)
-  Ubuntu 20.04

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Hi, 

Thank you so much for opening this issue and fuzzing acvm!

I checked the `master` branch and this issue seems to be fixed. Can you confirm?

**Comment by pventuzelo** [comment]
Hey, I just checked and it is not fixed

**Comment by kevaundray** [comment]
> Hey, I just checked and it is not fixed

Thanks for checking -- I've added the test mentioned above in PR https://github.com/noir-lang/acvm/pull/188

It's passing on my laptop, so we can use that PR to reproduce

**Comment by kevaundray** [comment]
This issue seems to only pop up on linux -- I'll push a fix using `try_reserve`

**Comment by kevaundray** [comment]
For clarity:

The issue is that [Vec::with_capacity](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.with_capacity) will panic `if the new capacity exceeds isize::MAX bytes`.  

In our case this is `num_opcodes * size_of<Opcode>` so if a malicious person sets num_opcodes appropriately, they can make `with_capacity` panic with an OOM error. 

The fix is to use `try_reserve` which will return an error if we cannot allocate `num_opcodes * size_of<Opcode>` bytes.

**Comment by kevaundray** [comment]
It also seems that the allocator on Mac systems will not panic, while on Ubuntu it will panic

**Comment by kevaundray** [comment]
Closing as #188 has been merged -- Thanks for finding this!
