### ISSUE TITLE
Suggestion: Add a way to indicate dependency between opcodes

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#189]
### Problem

Currently the Memory opcodes are all dependent on each other. The current way we show this in the code, is by having all of the Memory opcodes live in one Block structure. If one of them is not solvable, then the solver does not attempt to solve the rest of the memory opcodes.

Internally, I have been calling these types of opcodes "non-atomic"

### Proposed solution

There is no proposed solution. This is a tracking issue to see if we can get a better abstraction to indicate this dependency between opcodes, which allows us to not solve further opcodes if the previous one was not solavable.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
This is unnecessary under the assumption that ACIR can be executed in a single pass, right?

**Comment by TomAFrench** [comment]
Closing this as each opcode is assumed to be solvable when executed under the stepwise ACVM model.
