### ISSUE TITLE
Add cargo smart-release

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#19]

**Comment by phated** [comment]
[cargo-smart-release](https://crates.io/crates/cargo-smart-release) seems great! And it even mentions they use the same Conventional Commits spec as I suggested in Noir. I think the reason I'd lean towards release-please is the ability to share workflows across various projects that may be rust, typescript, etc.

What do you think?

**Comment by kevaundray** [comment]
Yeah I think a homogenous approach would be better.

My only point towards `cargo-smart-release` was the fact that it _seems_ to recognise workspaces, but we can get the same functionality that I would like by doing `feat(acvm)`, `feat(acir)`, feat({workspace_name})`

**Comment by kevaundray** [comment]
(Keeping this issue open until we switch to release-please)

**Comment by phated** [comment]
Oh yeah, release-please has cargo-workspace support but you have to move away from specifying the version in the workspace file so it can manage the crates independently, which I felt was too heavy-handed/overkill for the noir repo but maybe it makes sense to diverge for this repo.

**Comment by kevaundray** [comment]
Closing this as we are using release-please
