### ISSUE TITLE
ACVM Backend functions should be fallible

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm#235]
### Problem

Currently, a backend needs to panic if it does something fallible and that thing fails. This is not ideal because then Nargo or whatever other backend orchestrator is not in control of the errors.

### Proposed solution

Make all the functions return Result type. Define an error type that can be consumed by orchestrators.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
For context see the usage of `expect` in https://github.com/TomAFrench/acvm-backend-groth16/blob/master/src/proof_system.rs
