### ISSUE TITLE
Should `preprocess` be two functions: `generate_proving_key` and `generate_verification_key`?

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm#256]
### Problem

Currently, we require a `preprocess` function on the ProofSystem trait that needs to return the proving key and verification key; however the verifier might only need a verification key. Alternatively, backends such as https://github.com/TomAFrench/acvm-backend-groth16 generate the pk and vk at the same time.

### Proposed solution

Figure out if we want to split these or if it would cause too much friction when implementing various backends.

### Alternatives considered

Leave it as is.

### Additional context

See thread at https://github.com/noir-lang/acvm/pull/231#discussion_r1183490054 for more discussion

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Generally they are generated at the same time in a one-off relative expensive operation. So I think its fine to have it as is.
