### ISSUE TITLE
Should we make BlackBox Functions heterogenous?

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#29]
Currently all black box functions are defined to look the same via a FuncDefinition struct. It is however possible to have a similar structure to Directives and have each black box function define what unique types they require

**Comment by kevaundray** [comment]
One thing to consider is how the API will be used and which is more convenient and safe

**Comment by kevaundray** [comment]
See [here](https://github.com/noir-lang/noir/pull/647#discussion_r1071439411) for more context into why this could be a goo advantage.

For AND gate, the num_bits parameter is technically not needed for both inputs

**Comment by guipublic** [comment]
I answered those points in #53. Here the summary:
Non blackbox functions should be specific and have heterogeneous input
blackbox (i.e custom) functions should have homogenous input, but we should not require a num_bits for every witness.

**Comment by TomAFrench** [comment]
Resolved in #269
