### ISSUE TITLE
Needs release token

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm#301]
### Problem

We turned on MQ on this project, but didn't have any status checks, so things were merging immediately. I've now enabled required checks, but the release can't be cut. 

### Proposed solution

Switch to using a release token, which means we need to generate a token for this repo.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
I have added `ACVM_RELEASES`
