### ISSUE TITLE
Add ability to specify message length as a witness for all hash functions

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#320]
### Problem

See Issue #313 for the Keccak variant.

This however makes Keccak seem special when infact this property can be applied to all hash functions, albeit they will be implemented differently internally since not all hash functions are `sponge_absorb`.

### Happy Case

Add the ability to specify the message length as a witness for all hash functions

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Closing as we're changing to implementing the internal sponge functions rather than a monolithic version which takes an arg.
