### ISSUE TITLE
Implement Add trait for Witness to produce an Expression

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#321]
### Problem

We can implement Add for two Witness instances and produce an Expression.

### Happy Case

Code roughly would be:

```
impl Add<Witness> for Witness {
    type Output = Expression;

    fn add(self, rhs: Witness) -> Self::Output {
        Expression::from(self) + Expression::from(rhs)
    }
}
```

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@vicyyn This is a good first issue, if you are interested

**Comment by vicyyn** [comment]
Looking into this, thanks 😁
