### ISSUE TITLE
Pallas curve that can be used for zcash halo2

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/acvm#323]
### Problem

Bn254 can't be used in the original halo2 implementation by zcash

### Happy Case

This shouldn't affect current Noir frontend and backend. simply adding the scalar field of pallas curve should work

### Would you like to submit a PR for this Issue?

Maybe

**Comment by TomAFrench** [comment]
Closing as this repo is archived. We can consider new curves on the main repo.
