### ISSUE TITLE
Refactor Logging

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/acvm#348]
### Problem

Currently `Directive::Log` exclusively works with println statements by printing to stdout while solving the opcode. This is not ideal as there are multiple ways that someone way want to access logging information in their Noir circuit (writing to file, log traces in memory, etc.). The caller of the VM rather than the VM itself should be handling the logs. 

We should refactor the Log directive or simply remove it to use the new Brillig opcode.

### Happy Case

Remove Log opcodes entirely 
A caller should be able to implement logging using the Brillig opcode. The Brillig opcode has a foreign call instruction that allows the caller to execute and inject information from outside the Brillig VM execution. A caller who wishes to implement logging can generate Brillig bytecode to make a foreign call with the specific type of log they wish to perform (println, write to a file, etc.). The caller would then differentiate based upon the foreign function name what they wish to do with the information provided to the function. The compiler generating the bytecode would have to also include some information such as the ABI of the value they are looking to log for the caller to execute their logging logic upon.

### Alternatives Considered

Refactor to a Log ACIR opcode
This would simply store Log information such as witnesses and an ABI which the caller wishes to follow for this data type (single variable, array, struct, etc.). The caller would have access to the solved witness at the end of the ACVM execution and can construct the appropriate log among the solved opcodes. 

When the Log directive was first added ACVM did not have an Oracle (foreign call) opcode. This approach was a better alternative to the current way logging is done when the VM did not have an explicit way to handle foreign calls. With the caller able to execute outside logic outside of the ACVM environment logging does not have to be a part of the ACIR explicitly at all. 

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@vezenovm whats the status of this?

**Comment by vezenovm** [comment]
Finished with this: https://github.com/noir-lang/noir/issues/1615
