### ISSUE TITLE
feat(brillig): error on uninitialized memory read

### ISSUE THREAD

**Issue by ludamad** [noir-lang/acvm#352]
### Problem

Brillig currently reads 0 on uninitialized memory. This should continue to be the semantics of the circuit, but for simulation it might be best to error on uninitialized memory to catch potentially miscompiled programs (e.g. off by 1 read error in compile) or array out of bounds reads (e.g. also off by 1, but user error with index)

### Happy Case

Happiest is we never hit this either way as we always initialize read memory. But, if a user makes a mistake on array index and reads out of bounds, we should panic if we can

### Alternatives Considered

Just read 0. OK, simple, but giving up opportunity to quickly catch errors

### Would you like to submit a PR for this Issue?

No

**Comment by ludamad** [comment]
@kevaundray open to thoughts, @sirasistant and I think of this as 'nice to have'

**Comment by kevaundray** [comment]
> we should panic if we can

The VM panicking (stopping execution and unwinding the stack) can be problematic for WASM/JS environments so we should return an error if the user gives the wrong input in these cases

**Comment by ludamad** [comment]
Yes right, I meant more generally error if we can

**Comment by TomAFrench** [comment]
Closed by https://github.com/noir-lang/acvm/pull/468

**Comment by TomAFrench** [comment]
Ah, this is for brillig
