### ISSUE TITLE
Replace `HashToField128Security` with a `FieldFromBeBytes` black box function

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm#358]
### Problem

The `HashToField128Security` opcode performs a blake2s hash and converts the result to a field element, it's then roughly equivalent to `Field::from_be_bytes(blake2s(data))`.

This has a few downsides:
- We're tying the "hash to a field" element to the `blake2s` hash function. Backends which don't support `blake2s` then can't implement to the "hash to a field" functionality.
- It hides the fact that we're performing a `blakes2s` hash function so developers will need to know this when interacting with code which uses `HashToField128Security`.

### Happy Case

We should remove  `HashToField128Security` and replace it with a black box function which exposes the functionality for implementing `Field::from_be_bytes`.

This will allow us to have the "hash to a field" functionality without tying it to `blake2s` so developers can use whichever hash function works best for their usecase.

### Would you like to submit a PR for this Issue?

Yes

**Comment by kevaundray** [comment]
Closing as hash_to_field blackbox is no longer used
