### ISSUE TITLE
Refactor ACVM solver to allow tracking internal state

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm#383]
### Problem

Much of the state transitions in the ACVM are unnecessarily exposed or even outsourced to the caller due to the fact that the ACVM has no internal state. This causes issues such as described in #382. For example:

- When the ACVM encounters a foreign call, it aborts execution while returning the foreign calls along with a list of unsolved opcodes. The caller is then expected to manipulate those foreign call's directly, create new opcodes to represent their resolution, insert these handcrafted opcodes into the list of opcodes to execute and then restart the ACVM with this new set of opcodes.
- We require the caller to construct a `Blocks` instance and pass in a mutable reference to `acvm::pwg:solve`. They must then persist this across multiple invocations of `acvm::pwg:solve` as the ACVM cannot maintain track over its partial execution of `Block` opcodes itself.

### Happy Case

Rather than having a stateless function we can represent the ACVM as an `ACVM` struct as we do for the Brillig VM.

```rust
struct ACVM {
  backend: PartialWitnessGenerator
  witness_map: WitnessMap,
  blocks: Blocks
  opcodes: Vec<Opcode> 
}

impl ACVM {
  fn solve() -> ACVMStatus {
    // Do stuff
  }
}
```

This struct would encapsulate any internal state of the ACVM.

### Would you like to submit a PR for this Issue?

Yes

**Comment by ludamad** [comment]
Agreed with this, I liked having the resolution list instead of patching bytecode in brillig
