### ISSUE TITLE
Epic: ACIR debugger

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm#404]
# Motivation

We have a separate epic for a Noir debugger in https://github.com/noir-lang/noir/issues/1723 however a prerequisite for this is to create a debugger for ACIR code. Once this is

- An ACIR debugger is a necessary prerequisite for Noir debugger.
  - i.e. before we can create breakpoints/inspect relevant variables in Noir code, we must be able to create breakpoints in ACIR and inspect relevant witness indices in the witness map.
  - This would require building a mapping from expressions in Noir to a set of opcodes in ACIR.
      - This would need to be preserved through `acvm::compiler::compile`.
- An ACIR debugger can be reused by any other languages targeting the ACVM. 

# Requirements

This debugger should provide enough information that would allow the construction of a Noir debugger on top of it, we then need:
 - The ability to set breakpoints on particular opcodes in the ACIR.
   - Note that a Noir expression may be mapped to multiple ACIR opcodes so a decision would need to be made on how to address this.
    - Note that a Noir expression may be optimized away entirely and not feature in the ACIR code at all.
  - The ability to inspect the set of witness indices which were inputs/outputs for each opcode. Opcodes inherently give the set of relevant witnesses but we want to be able to distinguish how they're used.
    - This is sufficient to display all steps of execution due to the read-only nature of the witness map.
    - Some care is needed in the case of an unsatisfied constraint which attempts to write an inconsistent value to the witness map.

**Comment by kevaundray** [comment]
Removing as we have a debugger issue on noir
