### ISSUE TITLE
Should we specify that we only want to fallback in one place?

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#43]
Currently we can fallback in Noir and in ACVM. The noir version being more friendly since you can implement the fallback mechanism in a nicer langauge (Noir).

We need this fallback in ACVM because not every frontend will have a fallback mechanism like Noir and it avoids code deduplication. We do not necessarily need it in Noir however.

**Comment by TomAFrench** [comment]
We now only perform fallbacks in ACVM.
