### ISSUE TITLE
Get ACVM/ACVM_js in one repo

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/acvm#465]
As ACVM_js is mostly wrapper functionality around ACVM to enable it as library in browser, we should keep it in the same repository as ACVM. 

Solution needs to be found for having this crate part of Workspace, something that was not originally thought of. Alternatively we should keep acvm_js package out of workspace but be able to build it with acvm as dependency within same repository.

**Comment by kevaundray** [comment]
Can this be closed?
