### ISSUE TITLE
Add comparison/higher level opcodes

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#47]
# Description

In the spirit of moving more code into this layer, we can add comparison operators into the ACIR:

- LessThan(lhs : Expr, rhs : Expr, output : Witness)
- MoreThan(lhs : Expr, rhs : Expr, output : Witness)
- Eq(lhs : Expr, rhs : Expr, output : Witness)

# Note

We can take inspiration from Noir in order to list what we could potentially add

**Comment by guipublic** [comment]
There is not point to make ACIR and noir more complex.
