### ISSUE TITLE
Pass to replace all witness constants with constants

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#48]
# Description

It is possible to get an expre such as q_L * w_L + t = 0

Since q_L and t are constants, w_L can be solved and we can replace all instances of w_L with -t/q_L

# Note

In Barretenberg, put_constant is used to deliberately set some wires to be constants. We should figure out the usecases as to why this is being done.

**Comment by guipublic** [comment]
This is done by the simplification PR
