### ISSUE TITLE
Should BlackBoxFunc be changed to Func

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#52]
After some discussion, it was brought up that one could just view a BlackBoxFunction as a simple Function.

See [here](https://github.com/noir-lang/noir/pull/647#discussion_r1071418239) for more discussion

**Comment by guipublic** [comment]
The blackbox name does not make sense as everything is a blackbox, unless you know how each proving system is implementing them, but then this name should not depend on the knowledge of a particular person.

What make sense is to allow backends to define functions that are specific for them, which then require an additional identifier and a way for the backend to solve these functions. These are the features that blackboxfunction provides. 

Besides FunctionInput defines the witness inputs for blackboxfunction, so the naming is not coherent there.
As a result, BlackBoxFunction should be renamed into Function (or AcirFunction, or CustomFunction, or GadgetCall, with similar name for the inputs)
