### ISSUE TITLE
ACIR gates are blackbox functions

### ISSUE THREAD

**Issue by guipublic** [noir-lang/acvm#54]
# Description

ACIR 0.3 has removed the AND/XOR/RANGE/SHA256... gates and now treat them as 'blackbox functions'

## Expected behavior

Known functions, from bitwise AND to Sha256 are not blackbox function. They are completely specified and do not require a backend-specific solver.

## Bug

These common functions are now treated as blackbox functions which for instances means that the solver is not solving them anymore but rely on the solve_blackbox function implemented by every backends.
Another consequence of having them as a blackboxfunction is that they rely on FunctionInput which requires a num_bit value for every input witness. Our own Aztec proving system, is not even adapted to this interface, and I don't believe we want to change this. Consequently, using different num_bits for the inputs on ACIR will lead to errors, while this was not possible before as the ACIR specification would not make this possible.
Another example is the RANGE blackboxfunction which now has to return an error when used with more than one input.
Not only we now have to specify more data in ACIR, but it can also lead to more errors.

# To reproduce

Look for the commits referencing ACIR 0.3.0

**Comment by TomAFrench** [comment]
This looks to be resolved with heterogeneous bb functions
