### ISSUE TITLE
Tracking Issue: Compile Sway to ACIR

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm#67]
# Problem

Sway is another frontend by Fuel Labs that has the capabilities of being compiled to ACIR.

# Solution

TBD

# Alternatives considered

# Additional context

(If applicable.)

**Comment by nfurfaro** [comment]
This would be so cool to see. As the Alpha Swaylang user, I would love to be able to use that language for zk circuits too. That said, Noir feels very familiar coming from Sway.

**Comment by kevaundray** [comment]
We currently don't have much capacity to take this on, so I'll close until more interest is brought up for this
