### ISSUE TITLE
Should the Cargo.lock really be gitignored?

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm#87]
While adding release-please to acvm, I noticed that the lockfile isn't committed to the repository. Is this the correct for Rust projects?

**Comment by kevaundray** [comment]
For rust libraries, the Cargo.lock file is usually ignored and only checked in for Binaries: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by phated** [comment]
@kevaundray is there any config to avoid creating the lockfile during `cargo build`? npm allows this in the `.npmrc` file and it's important to ensure someone isn't accidentally relying on the gitignored lockfile.

**Comment by kevaundray** [comment]
> @kevaundray is there any config to avoid creating the lockfile during `cargo build`? npm allows this in the `.npmrc` file and it's important to ensure someone isn't accidentally relying on the gitignored lockfile.

I know there is a way to avoid creating one if it already exists with [--locked --frozen](https://doc.rust-lang.org/cargo/commands/cargo-build.html#manifest-options)

Was this what you wanted?

**Comment by phated** [comment]
I think that's still different because it assumes one exists. If we aren't going to check it in, we probably don't want it to be generated at all.

**Comment by phated** [comment]
Some quick searching seems to indicate this isn't possible with cargo 😢
